pipeline {
    agent {
        docker {
            image 'maven:3-alpine'
            args '-v /root/.m2:/root/.m2'
        }
    }
    stages {
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('SonarQube analysis') {
            steps {
                script {
                    // requires SonarQube Scanner 2.8+
                    scannerHome = tool 'SonarScanner';
                }
                //tools {
                //    sonarQube 'SonarScanner'
                //}
                //def scannerHome = tool 'SonarScanner 4.3.0.2102';
                withSonarQubeEnv('sonarqube') { // If you have configured more than one global server connection, you can specify its name
                   
                    sh "echo ${scannerHome}/bin/sonar-scanner";
                    //sh "sonar-scanner"
                }
            }
        }
        stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
            }
        }
    }
}
